# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ndcli < Formula
  desc "NetDefense CLI tool"
  homepage "https://github.com/netdefense-io/ndcli-releases"
  version "0.19.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v0.19.0/ndcli_0.19.0_darwin_amd64.tar.gz"
      sha256 "a7b2dc170667240381d9d3f80a696d90039cee82b5dca193fb6de98a360a8438"

      def install
        bin.install "ndcli"
        bin.install "netdefense-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v0.19.0/ndcli_0.19.0_darwin_arm64.tar.gz"
      sha256 "a3045eeb57f79718c6a82c0bbfc69b24d15a75cc5a80a8c6053bdc6a9ac91bda"

      def install
        bin.install "ndcli"
        bin.install "netdefense-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v0.19.0/ndcli_0.19.0_linux_amd64.tar.gz"
      sha256 "67ad876b190333aa4d4df319f5c03eca6a15a619d7d91861c0834b9eb4314524"
      def install
        bin.install "ndcli"
        bin.install "netdefense-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v0.19.0/ndcli_0.19.0_linux_arm64.tar.gz"
      sha256 "0194e56bbd078473a87286b0f5b83a964f0a04cf2a992c818ef3965f8d4b921e"
      def install
        bin.install "ndcli"
        bin.install "netdefense-mcp"
      end
    end
  end
end
