# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ndcli < Formula
  desc "NetDefense CLI tool"
  homepage "https://github.com/netdefense-io/ndcli-releases"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v0.1.3/ndcli_0.1.3_darwin_amd64.tar.gz"
      sha256 "6459deba8e857bb00914bc6906503faa2cfd5dbb91f57243f4a065e646e03928"

      def install
        bin.install "ndcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v0.1.3/ndcli_0.1.3_darwin_arm64.tar.gz"
      sha256 "92e86e898d77daf7d78babf8c0ecbbe13a19a654d925041c1ab1f21e4b8c2cc5"

      def install
        bin.install "ndcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v0.1.3/ndcli_0.1.3_linux_amd64.tar.gz"
      sha256 "91ca143941547bfb926264a8793fc85d8f79c0c0ece8eb1c5471496c939e407e"
      def install
        bin.install "ndcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v0.1.3/ndcli_0.1.3_linux_arm64.tar.gz"
      sha256 "c7118a28c089b731cb3508d36e1d9f73e30cf4b88b374fa9e00f21f1a85d0bac"
      def install
        bin.install "ndcli"
      end
    end
  end
end
