# This file was generated by GoReleaser. DO NOT EDIT.
cask "ndcli" do
  name "ndcli"
  desc "NetDefense CLI tool"
  homepage "https://github.com/netdefense-io/ndcli-releases"
  version "0.1.1-beta.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ndcli"

  on_macos do
    on_intel do
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v#{version}/ndcli_#{version}_darwin_amd64.tar.gz"
      sha256 "db1388a3bf9437c3cfc8d058651c8c1e6bfe0c5f079297558dfeb83270c12b3c"
    end
    on_arm do
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v#{version}/ndcli_#{version}_darwin_arm64.tar.gz"
      sha256 "4ab744e0557af3e24bea32e8b9b6c091c20f61409ce11fecdcf97656fa2a1e5b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v#{version}/ndcli_#{version}_linux_amd64.tar.gz"
      sha256 "aace5beabd4f15fe0be1f76819ffaa0e28f50d7c4d6241dd927ed75d914dd9b8"
    end
    on_arm do
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v#{version}/ndcli_#{version}_linux_arm64.tar.gz"
      sha256 "a1777e8084a64fe0a9cf34b8e24e31a4227325b668192f0268e0dca0ae2af6f4"
    end
  end

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/ndcli"]
  end

  # No zap stanza required
end
