# This file was generated by GoReleaser. DO NOT EDIT.
cask "ndcli" do
  name "ndcli"
  desc "NetDefense CLI tool"
  homepage "https://github.com/netdefense-io/ndcli-releases"
  version "0.1.0-beta.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ndcli"

  on_macos do
    on_intel do
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v#{version}/ndcli_#{version}_darwin_amd64.tar.gz"
      sha256 "ed9258de5609627c277f6834774ba50bd82a95081381f3ad3d7ea77c920470d1"
    end
    on_arm do
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v#{version}/ndcli_#{version}_darwin_arm64.tar.gz"
      sha256 "5e7daf4d5e0743ab18c1dff35e3316ec22cb0b23a75ecb74ff10160bd85fb4ee"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v#{version}/ndcli_#{version}_linux_amd64.tar.gz"
      sha256 "ac2c2426c6e204f5853537bfc2a5532703976e4942be4741a8608a476a23165d"
    end
    on_arm do
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v#{version}/ndcli_#{version}_linux_arm64.tar.gz"
      sha256 "947d4539aaa44fd1f98c2d0b04cbcd05fbbfdfd7096cc121c0ccea006058d1cc"
    end
  end

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/ndcli"]
  end

  # No zap stanza required
end
