# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ndcli < Formula
  desc "NetDefense CLI tool"
  homepage "https://github.com/netdefense-io/NDCLI"
  version "1.7.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v1.7.0/ndcli_1.7.0_darwin_amd64.tar.gz"
      sha256 "71e3ab94f42760c6e91f5241e25628868f858be7c75fd505f3216df25d02c7aa"

      define_method(:install) do
        bin.install "ndcli"
        bin.install "netdefense-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v1.7.0/ndcli_1.7.0_darwin_arm64.tar.gz"
      sha256 "f2b2465cbb97486be3ff7a5985132d81c80203d1e3474196b777a0d226e540df"

      define_method(:install) do
        bin.install "ndcli"
        bin.install "netdefense-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v1.7.0/ndcli_1.7.0_linux_amd64.tar.gz"
      sha256 "cedf9c707835504bcf2b9ca3c5c7a2c14198abde9b861ff43087be82c4b32607"
      define_method(:install) do
        bin.install "ndcli"
        bin.install "netdefense-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v1.7.0/ndcli_1.7.0_linux_arm64.tar.gz"
      sha256 "98e4f29784ee2914220a1ec1373fd7b2c508400b2419f4254faa18612c6039fb"
      define_method(:install) do
        bin.install "ndcli"
        bin.install "netdefense-mcp"
      end
    end
  end
end
