# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ndcli < Formula
  desc "NetDefense CLI tool"
  homepage "https://github.com/netdefense-io/NDCLI"
  version "1.26.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v1.26.0/ndcli_1.26.0_darwin_amd64.tar.gz"
      sha256 "df52d9bfd23663ccafe065b2d4ea48fcb0e0bb071b9aece7146651a7175bbf79"

      define_method(:install) do
        bin.install "ndcli"
        bin.install "netdefense-mcp"
        bin.install "netdefense"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v1.26.0/ndcli_1.26.0_darwin_arm64.tar.gz"
      sha256 "4c9d4a684d3ceb247f286c9550dd7f617cf96a2d04778ae6ea0d00155125eb89"

      define_method(:install) do
        bin.install "ndcli"
        bin.install "netdefense-mcp"
        bin.install "netdefense"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v1.26.0/ndcli_1.26.0_linux_amd64.tar.gz"
      sha256 "d8d9d780d9fc9799fef68b240d848d44eb55b39feeeca9a5930c865e159c2ebc"
      define_method(:install) do
        bin.install "ndcli"
        bin.install "netdefense-mcp"
        bin.install "netdefense"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v1.26.0/ndcli_1.26.0_linux_arm64.tar.gz"
      sha256 "6938910c572b6ac4cece5b56b26cd661e3a720e75258ec434058549adadce179"
      define_method(:install) do
        bin.install "ndcli"
        bin.install "netdefense-mcp"
        bin.install "netdefense"
      end
    end
  end
end
